spring.application.name=spring_boot_jpa_bookEx

server.port=8081

#jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#database connection
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:29889:xe
spring.datasource.username=system
spring.datasource.password=1234

#JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#컬럼명 prd_no와 같은 형식이 jpa 기본 컬럼형식
#entity 등 구성할 때 컬럼명을 prdNo와 같이 구성하면 prd_no와 같이 변경해버림
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl